sudo: false

language: cpp

branches:
  only:
    - master

os:
  - linux

env:
  global:
    secure: "Jo0Yx6pNQthCo15e4rxl8pWIGP3+BAvRMYn1kerklcLdkRx0PPt8bpEr9N42IkGq660RMLTsdtmMEoVT/Soo2o3gGeeFRW2k8gZQfawpM9P//nwsBtpdUGoutJz7gs/Oq1cVtWNAMcSBLpPbF6mM8uxV6XDv6ctuLcOPD3MclXNE9Lj/9xYFon4X3p7gTvIyadCbkLzaAB31UkfWYh+6jVSWAg0nI77ndYnP5qLOrLuBRlakAZeFvl9bUem0QeNN78MJ7t8JCs2rMvnUKEsNvu6vUoVhcdtlSTN6ofYhmURwZQjeicHvxUu6wV5QwFLOVQtOK0VIBGpqHnzkxTO6Z1L1YTER60a/9q3QfwhUOJvzxMciAu70jLodc03nq9lyV97/6RZY/DXmYAy+x1hTBbEx1TYL75DvTvfn5lOSjEDdX/+mdJLu+x45pgIVYQ1w9ruYoN9HwmvnwwspXic/GuEXSD3Qo59k1fAp7amjsjJvtJrlCbTbMT99pwdvNt9kjD8kxH0BEqQG1ogv4ofJuExDr2Kr+xqOqkHo2Z2gci2k8SWnuIj2dzuW8YtC8+mOy0kzHN5KhrKO3wopiC5YBTMtzfpZtGZp17qEbIKxPgqHlddW65IYc26SYoGEZveqcStC40BlYykWwOQ1U6rGSXE8mQh9fCfDllhu2U7SJiw="

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - yaml-cpp

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.15.3/cmake-3.15.3-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.15.3-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.15.3-Linux-x86_64 cmake
  - PATH=${DEPS_DIR}/cmake/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_install:
  - pip install --user cpp-coveralls

script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON && make && make test

after_success:
  - cd .. && coveralls -e test -e third_party --gcov-options '\-lp'
  - cd build && doxygen docs/Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
