sudo: false

language: cpp

branches:
  only:
    - master

os:
  - linux

addons:
  apt:
    packages:
      - doxygen
      - graphviz

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.15.3/cmake-3.15.3-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.15.3-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.15.3-Linux-x86_64 cmake
  - PATH=${DEPS_DIR}/cmake/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_install:
  - pip install --user cpp-coveralls

script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON && make && make test

after_success:
  - coveralls -e test -e third_party
  - doxygen docs/Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master