sudo: false

language: cpp

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - graphviz

os:
  - linux

before_install:
  - pip install --user cpp-coveralls

script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && make && ./test/Tester
  - doxygen docs/Doxyfile

after_success:
  - coveralls --exclude test --exclude third_party --gcov-options '\-lp'

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master